theme: minima

title: Ben's Blog
author: Benjamin Phan
email: bphan1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  Benjamin's Blog.
  
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  bphan1-jpg

show_excerpts: true # set to false to remove excerpts on the homepage
